ssim/config/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('symantec.ssim.config.views',
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>[^/]+)/distribute$', 'distribute_config'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/agents-tab$', 'config_agents'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/general-tab$', 'config_general'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/options-tab$', 'config_options'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/filter-tab$', 'config_filter'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/aggregator-tab$', 'config_aggregator'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/sensor-tab$', 'sensor_tab'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/sensors/(?P<selected_sensor>.*)$', 'config_sensors'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/sensor/(?P<sensor_name>[^/]*)$', 'config_sensor'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/sensor/(?P<sensor_name>[^/]+)/delete$', 'delete_sensor'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>.+)/sensor/(?P<sensor_name>[^/]+)/change-status$', 'change_sensor_status'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/config/(?P<config_name>[^/]+)/$', 'config_by_name'),
)

ssim/events/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('symantec.ssim.events.views',
    (r'^(?P<address>[^/]+)/$', 'index'),
    (r'^(?P<address>[^/]+)/events$', 'get_events'),
    (r'^(?P<address>[^/]+)/select-archive$', 'get_archives'),
    (r'^(?P<address>[^/]+)/event/(?P<guid>[^/]+)$', 'get_event'),
    (r'^(?P<address>[^/]+)/event_stats$', 'get_event_stats'),
    (r'^(?P<address>[^/]+)/queries$', 'get_query_groups'),
)

ssim/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('symantec.ssim.views',
    (r'^(?P<address>[^/]+)/login/$', 'login'),
    (r'^(?P<address>[^/]+)/locations$', 'locations'),
    (r'^(?P<address>[^/]+)/products$', 'products'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)$', 'config_by_product_id'),
    (r'^(?P<address>[^/]+)/product/(?P<productID>\d+)/create-config/(?P<config_name>.+)$', 'create_config'),
    (r'^(?P<address>[^/]+)/products/(?P<client>[^/]+)$', 'client_products'),
    (r'^ldap/$', 'test_ldap'),
    (r'^(?P<address>[^/]+)/$', 'index'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from symantec.authuser.models import *
from symantec.authuser.admin import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^symantec/', include('symantec.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^machines/', include('symantec.machines.urls')),
    (r'^ssim/', include('symantec.ssim.urls')),
    (r'^ssim/config/', include('symantec.ssim.config.urls')),
    (r'^ssim/events/', include('symantec.ssim.events.urls')),
    (r'^$', include('symantec.machines.urls')),
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'authuser/login.html'}),
    (r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT+'/css'}),
    (r'^img/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT+'/img'}),
    (r'^js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT+'/js'})
)

machines/models.py
from django.db import models
from django.contrib.auth.models import User

class Machine(models.Model):
    address = models.IPAddressField('Host Address', unique=True)
    name = models.CharField('Host Name', max_length=200, unique=True)
    os_name = models.CharField('OS', max_length=200)
    location = models.CharField('Location', max_length=1024, null=True, blank=True)
    user = models.ForeignKey(User, null=True, blank=True)
    info = models.CharField('Information', max_length=8192, null=True, blank=True)
    comments = models.CharField('Comments', max_length=1024, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

	#...
    def __unicode__(self):
        return self.name


	

ssim/config/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response

from symantec.ssim.utils import helper as utils
from symantec.ssim.utils import location
from symantec.ssim.utils import configuration

from symantec.ssim.exceptions import *
from django.shortcuts import redirect

from symantec.ssim.config.general import GeneralForm
from symantec.ssim.config import sensor
from symantec.ssim.config import agents
from symantec.ssim.config import general
from symantec.ssim.exceptions import *

def index(request, address = None):

    ldap_connection = utils.get_ldap_connection(request.session, address)
    if ldap_connection == None:
        return redirect('symantec.ssim.views.login', address=address)

    return render_to_response('ssim/index.html', {'address':address},
        mimetype="text/html")

def config_by_name(request, address, productID, config_name):
    ldap_connection = utils.get_ldap_connection(request.session, address)
    ldap_info = request.session['ldap'][address]
    (product_instance, config_root, config) = configuration.get_config_by_name(ldap_connection, ldap_info['domain'], productID, config_name)
        
    return render_to_response('ssim/config/edit.html', {'product':product_instance, 'config':config, 'address':address},
        mimetype="text/html")

def config_general(request, address, productID, config_name):
    ldap_connection = utils.get_ldap_connection(request.session, address)

    configDN = request.POST.get('configDN', None)
    config = None;
    if configDN == None:
        ldap_info = request.session['ldap'][address]
        (product_instance, config_root, config) = configuration.get_config_by_name(ldap_connection, ldap_info['domain'], productID, config_name)
    else:
        config = configuration.get_config_by_dn(ldap_connection, configDN)

    if request.method == 'GET':
        data = {'name':config.name,
                'desc':config.desc,
                'updated_at':config.updated_at,
                'configDN':config.dn
               }
        form = GeneralForm(initial = data)
    else:
        form = GeneralForm(request.POST)
        if form.is_valid():
            # save data
            general.update_config(ldap_connection, config, form)

    return render_to_response('ssim/config/general.html', {
        'productID':productID,
        'config':config,
        'form':form,
        'address':address,
        'action':request.path},
        mimetype="text/html")

def config_filter(request, address, productID, config_name):
    pass

def config_aggregator(request, address, productID, config_name):
    pass

def sensor_tab(request, address, productID, config_name,):
    return render_to_response('ssim/config/sensor-tab.html', {'productID':productID, 'config_name':config_name, 'address':address},
        mimetype="text/html")

def delete_sensor(request, address, productID, config_name, sensor_name):
    ldap_connection = utils.get_ldap_connection(request.session, address)

    configDN = request.POST.get('configDN', None)
    config = None;
    if configDN == None:
        ldap_info = request.session['ldap'][address]
        (product_instance, config_root, config) = configuration.get_config_by_name(ldap_connection, ldap_info['domain'], productID, config_name)
    else:
        config = configuration.get_config_by_dn(ldap_connection, configDN)

    sensor_config = configuration.get_sensor_config(ldap_connection, config)
    sensor_xml = sensor.remove_sensor_from_xml(sensor_config.data, sensor_name)
    # save data
    configuration.update_settings(ldap_connection, sensor_config.dn, sensor_xml)
    
    return redirect("/ssim/config/%s/product/%s/config/%s/sensors/" %
        (address, productID, config_name))

def config_sensor(request, address, productID, config_name, sensor_name):
    ldap_connection = utils.get_ldap_connection(request.session, address)
    
    configDN = request.POST.get('configDN', None)
    config = None;
    if configDN == None:
        ldap_info = request.session['ldap'][address]
        (product_instance, config_root, config) = configuration.get_config_by_name(ldap_connection, ldap_info['domain'], productID, config_name)
    else:
        config = configuration.get_config_by_dn(ldap_connection, configDN)

    sensor_config = configuration.get_sensor_config(ldap_connection, config)

    #check that sensor_name is specified
    if not sensor_name or len(sensor_name) == 0:
        sensor_name = None

    #create dynamic form !!!
    form_clazz = sensor.get_sensor_form(sensor_config.data, sensor_name = sensor_name)
    sensor_instance = form_clazz.sensor
    # check request method
    form = None
    refresh_sensor_list = False
    is_sensor_saved = False
    if request.method == 'GET':
        form = form_clazz()
    elif request.method == 'POST':
        form = form_clazz(request.POST)
        if form.is_valid():
            saved_sensor_name, sensor_xml = form.update_xml()
            # save data
            configuration.update_settings(ldap_connection, sensor_config.dn, sensor_xml)
            is_sensor_saved = True
            if not sensor_name:
                sensor_name = saved_sensor_name
                refresh_sensor_list = True

    return render_to_response('ssim/config/sensor.html', {'productID':productID, 
        'config':config,
        'sensor':sensor_instance,
        'form':form,
        'address':address,
        'action':request.path,
        'update_item_list':refresh_sensor_list,
        'sensor_saved':is_sensor_saved},
        mimetype="text/html")

def change_sensor_status(request, address, productID, config_name, sensor_name):
    try:
        ldap_connection = utils.get_ldap_connection(request.session, address)

        configDN = request.POST.get('configDN', None)
        config = None;
        if configDN == None:
            ldap_info = request.session['ldap'][address]
            (product_instance, config_root, config) = configuration.get_config_by_name(ldap_connection, ldap_info['domain'], productID, config_name)
        else:
            config = configuration.get_config_by_dn(ldap_connection, configDN)

        sensor_config = configuration.get_sensor_config(ldap_connection, config)
        status, sensor_xml = sensor.change_status(sensor_config.data, sensor_name)
        # save data
        configuration.update_settings(ldap_connection, sensor_config.dn, sensor_xml)
    except Exception as ex:
        status = ex
    return HttpResponse(status,
            mimetype='text/plain')

def config_sensors(request, address, productID, config_name, selected_sensor):
    ldap_connection = utils.get_ldap_connection(request.session, address)

    configDN = request.POST.get('configDN', None)
    config = None;
    if configDN == None:
        ldap_info = request.session['ldap'][address]
        (product_instance, config_root, config) = configuration.get_config_by_name(ldap_connection, ldap_info['domain'], productID, config_name)
    else:
        config = configuration.get_config_by_dn(ldap_connection, configDN)

    sensor_config = configuration.get_sensor_config(ldap_connection, config)
    sensor_list = sensor.get_all_sensors(sensor_config.data)

    #define selected and first link
    first_sensor = None
    if len(sensor_list) > 0:
        first_sensor = sensor_list[0].name
    # render
    return render_to_response('ssim/config/sensors.html', {
                'productID':productID,
                'config':config,
                'sensor_config': sensor_config,
                'sensors':sensor_list,
                'first_link':first_sensor,
                'selected_link':selected_sensor,
                'address':address,
                },
                mimetype="text/html")

def config_options(request, address, productID, config_name):
    pass

def distribute_config(request, address, productID, config_name):
    status = 'success'
    try:
        ldap_connection = utils.get_ldap_connection(request.session, address)

        configDN = request.POST.get('configDN', None)
        config = None;
        if configDN == None:
            ldap_info = request.session['ldap'][address]
            (product_instance, config_root, config) = configuration.get_config_by_name(ldap_connection, ldap_info['domain'], productID, config_name)
        else:
            config = configuration.get_config_by_dn(ldap_connection, configDN)
        if len(config.elements) > 0:
            utils.distribute_config(address, request.session, config.elements)
        else:
            status = 'There are no Agents related with current configuration'
    except Exception as ex:
        status = ex

    return HttpResponse(status,
            mimetype='text/plain')

def config_agents(request, address, productID, config_name):
    ldap_connection = utils.get_ldap_connection(request.session, address)

    configDN = request.POST.get('configDN', None)
    config = None;
    if configDN == None:
        ldap_info = request.session['ldap'][address]
        (product_instance, config_root, config) = configuration.get_config_by_name(ldap_connection, ldap_info['domain'], productID, config_name)
    else:
        config = configuration.get_config_by_dn(ldap_connection, configDN)

    #save data
    params = request.GET
    if request.method == 'POST':
        params = request.POST
        agents.save(ldap_connection, config, request.POST.getlist('agents'))

    #get all agents and agents references
    ldap_info = request.session['ldap'][address]
    all_agents = location.all(ldap_connection, ldap_info['domain'])
    linked_agents = []
    if len(config.elements_names) > 0:
        linked_agents = location.all(ldap_connection, ldap_info['domain'], config.elements_names)

    # filter all_agents
    for item in linked_agents:
        if item in all_agents:
            all_agents.remove(item)
    
    return render_to_response('ssim/config/agents-tab.html', {'productID':productID,
        'config':config,

templates/ssim/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Author's original DTD was XHTML 1.0 Strict -->
<html>
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
    <link rel="stylesheet" type="text/css" href="/css/ssim/base.css" />

    <link rel="stylesheet" type="text/css" href="/css/ssim/sunny/jquery-ui-1.7.2.custom.css" />

    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery-ui-1.7.2.custom.min.js"></script>

    <script type="text/javascript" src="/js/ssim.js"></script>
    <link rel="stylesheet" type="text/css" href="/css/ssim/forms.css" />

    <link rel="stylesheet" type="text/css" href="/css/ssim/toolbar.css" />
    <script type="text/javascript" src="/js/toolbar.js"></script>

    <script type="text/javascript" src="/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/js/splitter.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/ssim/notificationmsg.css" />
    <script type="text/javascript" src="/js/ui.notificationmsg.js"></script>

    <script>
        $().ready(function() {
                $("#mainSplitter").splitter({
                        type: "v",
                        outline: true,
                        minLeft: 100, sizeLeft: 300, minRight: 300,
                        resizeToWidth: true,
                        cookie: "vsplitter",
                        anchorToWindow: true,
                        accessKey: 'I'
                });
        });
    </script>

    <title>SSIM administrations</title>
</head>
<body>
    <div id="header">{% block header %}<h1 class="symantec">SSIM Client</h1>{% endblock %}</div>

    <div id="mainSplitter">
        <div id="mainmenu">
            {% block mainmenu %}
                Loading...
            {% endblock %}
        </div>
        <div id="content">{% block content %}Content.{% endblock %}</div>
    </div>
    <div id="footer" class="fg-toolbar ui-widget-header ui-corner-all ui-helper-clearfix">
        {% block footer %}
            <div class="fg-buttonset fg-buttonset-single ui-helper-clearfix">
                <a href="/ssim/{{ address }}/products" class="link_for_mainmenu fg-button ui-state-default ui-state-active ui-priority-primary ui-corner-left" title="Products">products</a>
                <a href="/ssim/{{ address }}/locations" class="link_for_mainmenu fg-button ui-state-default ui-priority-primary ui-corner-right" title="Agents">agents</a>
            </div>
            <a href="/ssim/events/{{ address }}" id="events" class="fg-button ui-state-default ui-priority-primary ui-corner-all" title="Events" target="_blank">events</a>
        {% endblock %}
    </div>

    <!-- Notification block -->
    <script type="text/javascript">
        $(document).ready(function(){
            $('#msg1').notificationmsg({period: 1000});
            $('#closebutton').click(function(){ $('#msg1').notificationmsg('hide'); });
        });

        function notify(text)
        {
            var animStyle = 'slide'//fade,slidethru
            $("#modalbody").text(text);
            $('#msg1').notificationmsg({animation:animStyle});
            $('#msg1').notificationmsg('show');
        }
    </script>


    <div id="msg1">
        <div id="modal">
            <div class="modaltop">
                <div class="modaltitle">Notification</div>
                    <span id="closebutton" style="cursor:pointer">
                        <img alt="Hide Popup" src="/img/ssim/close_vista.gif" width="28" height="15" border="0" />
                    </span>
                </div>
            <div class="modalbody" id="modalbody">
                Form saved
            </div>
        </div>
    </div>
    <!-- End of Notification block -->

  </body>

  <script>
        $(document).ready(function() {
                load_data('/ssim/{{ address }}/products', '#mainmenu');
        });

        $('a.link_for_mainmenu').click(function(event){
            event.preventDefault();
            load_data($(this).attr('href'), '#mainmenu')
            return false;
        });

        $('#events').click(function(event){
            event.preventDefault();
            var win = $(this).attr('href').replace(/[/:.]/g,"_");
            window.open( $(this).attr('href'), win, "width=950,height=600,menubar=no,toolbar=no,location=no,resizable=yes" );
            return false;
        });
  </script>
  
</html>

templates/ssim/client_products.html
<div class="frame-header ui-widget-header ui-corner-all ui-helper-clearfix">Product List</div>
<div>
    <ul>
        {% for product in products %}
            <li>
                <a class="content_list" href="/ssim/{{ address }}/product/{{ product.productID }}">{{ product.name }}</a>
            </li>
        {% endfor %}
    </ul>
</div>

<script>
    $('a.content_list').click(function(event){
        event.preventDefault();
        load_data($(this).attr('href'), '#content')
        return false;
    });
</script>

templates/ssim/config_list_toolbar.html
<div class="fg-toolbar ui-helper-clearfix" id="config_list_toolbar">
    <a id="add"    href="/ssim/{{ address }}/product/{{ product.productID }}/create-config/" class="fg-button ui-state-default fg-button-icon-solo  ui-corner-all" title="Add new configuration"><span class="ui-icon ui-icon-plus"></span> Add</a>
    <a id="remove" href="#" class="fg-button ui-state-default fg-button-icon-solo  ui-corner-all" title="Remove configuration"><span class="ui-icon ui-icon-minus"></span> Remove</a>
</div>

<script type="text/javascript">
	$(function() {
		$("#delete_config_dialog").dialog({
			bgiframe: true,
                        autoOpen: false,
			resizable: false,
			height: 180,
			modal: true,
			overlay: {
				backgroundColor: '#000',
				opacity: 0.5
			},
			buttons: {
				'Delete': function() {
					$(this).dialog('close');
				},
				Cancel: function() {
					$(this).dialog('close');
				}
			}
		});
	});

        var name = $("#name"), allFields = $([]).add(name), tips = $("#validateTips");


        function updateTips(t) {
                tips.text(t).effect("highlight",{},1500);
        }

        function checkLength(o,n,min,max) {

                if ( o.val().length > max || o.val().length < min ) {
                        o.addClass('ui-state-error');
                        updateTips("Length of " + n + " must be between "+min+" and "+max+".");
                        return false;
                } else {
                        return true;
                }

        }

        function checkRegexp(o,regexp,n) {

                if ( !( regexp.test( o.val() ) ) ) {
                        o.addClass('ui-state-error');
                        updateTips(n);
                        return false;
                } else {
                        return true;
                }
        }

        $("#create_config_dialog").dialog({
                bgiframe: true,
                autoOpen: false,
                height: 200,
                modal: true,
                buttons: {
                        'Create a configuration': function() {
                                var bValid = true;
                                allFields.removeClass('ui-state-error');

                                bValid = bValid && checkLength(name,"name",3,16);
                                bValid = bValid && checkRegexp(name,/^[a-z]([0-9a-z_])+$/i,"\"Name\" may consist of a-z, 0-9, underscores, begin with a letter.");
                                if (bValid) {
                                        var button = $('#config_list_toolbar #add')
                                        load_data(button.attr('href') + name.val(), '#content');
                                        $(this).dialog('close');
                                }
                        },
                        Cancel: function() {
                                $(this).dialog('close');
                        }
                },
                close: function() {
                        allFields.val('').removeClass('ui-state-error');
                }
        });

</script>


<div id="delete_config_dialog" title="Delete selected configurations ?">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Selected confugurations will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>

<div id="create_config_dialog" title="Create new configuration">
	<p id="validateTips">Field "Name" is required.</p>

	<form>

		<label for="name">Name</label>
		<input type="text" name="name" id="name" class="text ui-widget-content ui-corner-all" />

	</form>
</div>

<script>
    $('#config_list_toolbar #add').click(function(event){
        event.preventDefault();
        $('#create_config_dialog').dialog('open');
        return false;
    });
    $('#config_list_toolbar #remove').click(function(event){
        event.preventDefault();
        $('#delete_config_dialog').dialog('open');
        return false;
    });
</script>

templates/ssim/configurations.html
<div class="frame-header ui-widget-header ui-corner-all ui-helper-clearfix">
    Configurations ({{ product.name }})
</div>
<div style="padding:10px;">
    <ul class="item_list" id="config_list">
        {% for config in configurations %}
            <li>
                <a href="#" class="item_status disabled" style="margin-right:10px;"><span>checkbox</span></a>
                <a class="content_list" href="/ssim/config/{{ address }}/product/{{ product.productID }}/config/{{ config.name }}/" configDN="{{ config.dn }}">{{ config.name }}</a>
            </li>
        {% endfor %}
    </ul>
    <br/>
    {% include 'ssim/config_list_toolbar.html' %}
</div>

<script>
    $(SetupButtons);
</script>

<script>
    var change_checkbox_state = function(event){
        event.preventDefault();
        var item = $(this)
        if( item.is('.disabled') ){
            item.removeClass('disabled');
            item.addClass('enabled');
        }
        else if( item.is('.enabled') ){
            item.removeClass('enabled');
            item.addClass('disabled');
        }
        else {
            alert(data);
        }
        return false;
    }
    $('#config_list a.item_status').click(change_checkbox_state);


    $('.content_list').click(function(event){
        event.preventDefault();
        post($(this).attr('href'), '#content',{'configDN':$(this).attr('configDN')})
        return false;
    });
</script>

templates/ssim/index.html
{% extends "ssim/base.html" %}

{% block content %}
    <div class="frame-header ui-widget-header ui-corner-all ui-helper-clearfix">
        SSIM {{ address }}
    </div>
{% endblock %}

templates/ssim/locations.html
<div class="frame-header ui-widget-header ui-corner-all ui-helper-clearfix">Clients</div>

<div>
    <ul>
        {% for client in clients %}
            <li>
                <a class="mainmenu" href="/ssim/{{ address }}/products/{{ client.address }}" locationDN="{{ client.dn }}">
                    {{ client.host }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
<script>
    $('a.mainmenu').click(function(event){
        event.preventDefault();
        post($(this).attr('href'), '#content',{'locationDN':$(this).attr('locationDN')})
        return false;
    });
</script>

templates/ssim/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-us" xml:lang="en-us" >
<head>
<title> | SSIM admin</title>
<link rel="stylesheet" type="text/css" href="/css/login.css" />
<link rel="stylesheet" type="text/css" href="/css/base.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/css/ie.css" /><![endif]-->
<meta name="robots" content="NONE,NOARCHIVE" />
</head>
<body class="login">

<!-- Container -->

<div id="container">
    <!-- Header -->
    <div id="header">
        <div id="branding">
            <h1 id="site-name">SSIM administration</h1>
        </div>
    </div>
    <!-- END Header -->

    <!-- Content -->
    <div id="content" class="colM">
        {% if error_message %}
            <p class="errornote">{{ error_message }}</p>
        {% endif %}
        <div id="content-main">
        <form action="" method="post" id="login-form">
          <div class="form-row">
            <label for="id_username">Address:</label> <input type="text" name="address" id="id_address" value="{{ address }}" />
          </div>
          <div class="form-row">

            <label for="id_username">Username:</label> <input type="text" name="username" id="id_username" />
          </div>
          <div class="form-row">

            <label for="id_password">Password:</label> <input type="password" name="password" id="id_password" />
            <input type="hidden" name="this_is_the_login_form" value="1" />
          </div>
          <div class="submit-row">
            <label>&nbsp;</label><input type="submit" value="Log in" />
          </div>
        </form>

        <script type="text/javascript">
        document.getElementById('id_username').focus()

        </script>
        </div>

        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

templates/ssim/products.html
<div class="frame-header ui-widget-header ui-corner-all ui-helper-clearfix">Collectors</div>

<div>
<ul>
    {% for product in products %}
        <li>
            <a class="mainmenu" href="/ssim/{{ address }}/product/{{ product.productID }}">{{ product.name }}</a>
        </li>
    {% endfor %}
</ul>
</div>

<script>
    $('a.mainmenu').click(function(event){
        event.preventDefault();
        load_data($(this).attr('href'), '#content')
        return false;
    });
</script>